# Generated by Django 5.0.3 on 2024-06-29 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Image', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username1', models.CharField(max_length=30)),
                ('username2', models.CharField(blank=True, max_length=30, null=True)),
                ('is_pvp', models.BooleanField()),
                ('is_pvai', models.BooleanField()),
                ('user1_answer', models.IntegerField()),
                ('user2_answer', models.IntegerField(blank=True, null=True)),
                ('ai_answer', models.IntegerField(blank=True, null=True)),
                ('tip_ai', models.CharField(blank=True, max_length=50, null=True)),
                ('winner', models.CharField(blank=True, max_length=30, null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='Image.image')),
            ],
        ),
    ]
